"""
Hospital_Management_System

Generated by ArchitectAI
"""

from fastapi import FastAPI

from app.api.health import router as health_router
from app.api.patients import router as patients_router
from app.api.doctors import router as doctors_router
from app.api.appointments import router as appointments_router

app = FastAPI(
    title="Hospital_Management_System",
    version="1.0.0",
)

app.include_router(health_router)
app.include_router(patients_router)
app.include_router(doctors_router)
app.include_router(appointments_router)


@app.get("/")
def root():

    return {
        "project": "Hospital_Management_System",
        "status": "running"
    }
