"""
ArchitectAI Project Packaging Generator

Generates deployment and documentation files
for dynamically generated backend projects.
"""

from pathlib import Path
import json

from generators.writer import FileWriter


class ProjectPackagingGenerator:

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.backend_dir = self.output_dir / "backend"

    def generate_requirements(self):
        content = """fastapi
uvicorn[standard]
sqlalchemy
pydantic
pytest
httpx
"""

        FileWriter.write(
            self.backend_dir / "requirements.txt",
            content,
        )

        print("✅ Generated requirements.txt")

    def generate_env_example(self):
        content = """# Generated Backend Configuration

APP_ENV=development
DEBUG=True

DATABASE_URL=sqlite:///./app.db

API_HOST=0.0.0.0
API_PORT=8000
"""

        FileWriter.write(
            self.backend_dir / ".env.example",
            content,
        )

        print("✅ Generated .env.example")

    def generate_dockerfile(self):
        content = """FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

        FileWriter.write(
            self.backend_dir / "Dockerfile",
            content,
        )

        print("✅ Generated Dockerfile")

    def generate_dockerignore(self):
        content = """__pycache__
*.pyc
*.pyo
*.pyd
.pytest_cache
.venv
venv
.env
app.db
*.db
.git
.DS_Store
"""

        FileWriter.write(
            self.backend_dir / ".dockerignore",
            content,
        )

        print("✅ Generated .dockerignore")

    def generate_gitignore(self):
        content = """__pycache__/
*.py[cod]
.venv/
venv/
.env
.pytest_cache/
*.db
app.db
.DS_Store
"""

        FileWriter.write(
            self.backend_dir / ".gitignore",
            content,
        )

        print("✅ Generated .gitignore")

    def generate_readme(
        self,
        project_name: str,
        entities,
    ):
        entity_names = [
            entity.name
            for entity in entities
        ]

        entities_text = "\n".join(
            f"- {name}"
            for name in entity_names
        )

        # Use a normal multi-line string without
        # nested Markdown code fences.
        content = f"""# {project_name}

Automatically generated by ArchitectAI Autonomous Tech Lead.

## Generated Entities

{entities_text}

## Technology Stack

- Python 3.12
- FastAPI
- SQLAlchemy
- Pydantic
- SQLite
- Pytest
- Docker

## Run Locally

Create and activate a virtual environment:

    python3 -m venv .venv
    source .venv/bin/activate

Install dependencies:

    pip install -r requirements.txt

Start the API:

    uvicorn app.main:app --reload

Swagger documentation:

    http://127.0.0.1:8000/docs

## Run Tests

    python3 -m pytest tests/ -v

## Docker

Build:

    docker build -t architectai-generated-api .

Run:

    docker run --rm -p 8000:8000 architectai-generated-api

## Architecture

    backend/
    ├── app/
    │   ├── api/
    │   ├── models/
    │   ├── repositories/
    │   ├── schemas/
    │   ├── services/
    │   ├── database.py
    │   └── main.py
    └── tests/

## Generated By

ArchitectAI Autonomous Tech Lead.

This backend was generated from natural-language requirements.
"""

        FileWriter.write(
            self.backend_dir / "README.md",
            content,
        )

        print("✅ Generated README.md")

    def generate_manifest(
        self,
        project_name: str,
        blueprint,
    ):
        entities = []

        for entity in blueprint.entities:
            fields = []

            for field in entity.fields:
                fields.append(
                    {
                        "name": field.name,
                        "type": field.type,
                    }
                )

            entities.append(
                {
                    "name": entity.name,
                    "fields": fields,
                }
            )

        relationships = []

        for relation in blueprint.relationships:
            relationships.append(
                {
                    "source": relation.source,
                    "target": relation.target,
                    "relationship_type": (
                        relation.relationship_type
                    ),
                    "foreign_key": relation.foreign_key,
                }
            )

        manifest = {
            "generator": "ArchitectAI",
            "project_name": project_name,
            "backend": "FastAPI",
            "database": "SQLite",
            "entities": entities,
            "relationships": relationships,
        }

        path = (
            self.backend_dir
            / "architectai_manifest.json"
        )

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        path.write_text(
            json.dumps(
                manifest,
                indent=4,
            ),
            encoding="utf-8",
        )

        print(
            "✅ Generated architectai_manifest.json"
        )

    def generate(
        self,
        project_name: str,
        blueprint,
    ):
        print("\n" + "=" * 60)
        print("📦 Packaging Generated Project")
        print("=" * 60)

        self.backend_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.generate_requirements()
        self.generate_env_example()
        self.generate_dockerfile()
        self.generate_dockerignore()
        self.generate_gitignore()

        self.generate_readme(
            project_name=project_name,
            entities=blueprint.entities,
        )

        self.generate_manifest(
            project_name=project_name,
            blueprint=blueprint,
        )

        print(
            "\n✅ Project packaging completed"
        )
