"""
ArchitectAI Project Packaging Generator

Generates deployment and documentation files
for dynamically generated backend projects.
"""

from pathlib import Path
import json

from generators.writer import FileWriter


class ProjectPackagingGenerator:

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.backend_dir = self.output_dir / "backend"

    def generate_requirements(self):
        content = """fastapi
uvicorn[standard]
sqlalchemy
pydantic
pytest
httpx
"""

        FileWriter.write(
            self.backend_dir / "requirements.txt",
            content,
        )

        print("✅ Generated requirements.txt")

    def generate_env_example(self):
        content = """# Generated Backend Configuration

APP_ENV=development
DEBUG=True

DATABASE_URL=sqlite:///./app.db

API_HOST=0.0.0.0
API_PORT=8000
"""

        FileWriter.write(
            self.backend_dir / ".env.example",
            content,
        )

        print("✅ Generated .env.example")

    def generate_dockerfile(self):
        content = """FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

        FileWriter.write(
            self.backend_dir / "Dockerfile",
            content,
        )

        print("✅ Generated Dockerfile")

    def generate_dockerignore(self):
        content = """__pycache__
*.pyc
*.pyo
*.pyd
.pytest_cache
.venv
venv
.env
app.db
*.db
.git
.DS_Store
"""

        FileWriter.write(
            self.backend_dir / ".dockerignore",
            content,
        )

        print("✅ Generated .dockerignore")

    def generate_gitignore(self):
        content = """__pycache__/
*.py[cod]
.venv/
venv/
.env
.pytest_cache/
*.db
app.db
.DS_Store
"""

        FileWriter.write(
            self.backend_dir / ".gitignore",
            content,
        )

        print("✅ Generated .gitignore")

    def generate_pytest_ini(self):
        content = """[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
"""
        FileWriter.write(
            self.backend_dir / "pytest.ini",
            content,
        )
        print("✅ Generated pytest.ini")

    def generate_openapi_spec(self):
        try:
            import subprocess
            import sys
            backend_path = str(self.backend_dir.resolve())
            script = f"""
import sys, json
sys.path.insert(0, {repr(backend_path)})
try:
    from app.main import app
    print("ARCHITECTAI_SPEC_START")
    print(json.dumps(app.openapi()))
    print("ARCHITECTAI_SPEC_END")
except Exception:
    import sys
    sys.exit(1)
"""
            res = subprocess.run(
                [sys.executable, "-c", script],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=self.backend_dir,
            )
            if res.returncode == 0 and "ARCHITECTAI_SPEC_START" in res.stdout:
                spec_json = res.stdout.split("ARCHITECTAI_SPEC_START")[1].split("ARCHITECTAI_SPEC_END")[0].strip()
                FileWriter.write(self.backend_dir / "openapi.json", spec_json)
                print("✅ Generated openapi.json")
        except Exception as e:
            print(f"⚠️ Could not generate openapi.json: {e}")

    def generate_readme(
        self,
        project_name: str,
        entities,
    ):
        entity_names = [
            entity.name
            for entity in entities
        ]

        entities_text = "\n".join(
            f"- {name}"
            for name in entity_names
        )

        # Use a normal multi-line string without
        # nested Markdown code fences.
        content = f"""# {project_name}

Automatically generated by ArchitectAI Autonomous Tech Lead.

## Generated Entities

{entities_text}

## Technology Stack

- Python 3.12
- FastAPI
- SQLAlchemy
- Pydantic
- SQLite
- Pytest
- Docker
- Kubernetes & Kustomize
- Helm 3

## Run Locally

Create and activate a virtual environment:

    python3 -m venv .venv
    source .venv/bin/activate

Install dependencies:

    pip install -r requirements.txt

Start the API:

    uvicorn app.main:app --reload

Swagger documentation:

    http://127.0.0.1:8000/docs

## Run Tests

    python3 -m pytest tests/ -v

## Docker

Build:

    docker build -t architectai-generated-api .

Run:

    docker run --rm -p 8000:8000 architectai-generated-api

## Kubernetes Deployment

Deploy all resources (Deployment, Service, ConfigMap, Ingress, HPA):

    kubectl apply -k k8s/

Port-forward service to test locally:

    kubectl port-forward service/{self.sanitize_k8s_name(project_name)}-service 8000:80

## Helm Deployment

Install chart:

    helm install {self.sanitize_k8s_name(project_name)} ./helm/{self.sanitize_k8s_name(project_name)}

Upgrade chart:

    helm upgrade {self.sanitize_k8s_name(project_name)} ./helm/{self.sanitize_k8s_name(project_name)}

## Architecture

    backend/
    ├── app/
    │   ├── api/
    │   ├── models/
    │   ├── repositories/
    │   ├── schemas/
    │   ├── services/
    │   ├── database.py
    │   └── main.py
    ├── k8s/
    │   ├── deployment.yaml
    │   ├── service.yaml
    │   ├── configmap.yaml
    │   ├── ingress.yaml
    │   ├── hpa.yaml
    │   └── kustomization.yaml
    ├── helm/
    │   └── {self.sanitize_k8s_name(project_name)}/
    │       ├── Chart.yaml
    │       ├── values.yaml
    │       └── templates/
    └── tests/

## Generated By

ArchitectAI Autonomous Tech Lead.

This backend was generated from natural-language requirements.
"""

        FileWriter.write(
            self.backend_dir / "README.md",
            content,
        )

        print("✅ Generated README.md")

    def generate_manifest(
        self,
        project_name: str,
        blueprint,
    ):
        entities = []

        for entity in blueprint.entities:
            fields = []

            for field in entity.fields:
                fields.append(
                    {
                        "name": field.name,
                        "type": field.type,
                    }
                )

            entities.append(
                {
                    "name": entity.name,
                    "fields": fields,
                }
            )

        relationships = []

        for relation in blueprint.relationships:
            relationships.append(
                {
                    "source": relation.source,
                    "target": relation.target,
                    "relationship_type": (
                        relation.relationship_type
                    ),
                    "foreign_key": relation.foreign_key,
                }
            )

        manifest = {
            "generator": "ArchitectAI",
            "project_name": project_name,
            "backend": "FastAPI",
            "database": "SQLite",
            "entities": entities,
            "relationships": relationships,
        }

        path = (
            self.backend_dir
            / "architectai_manifest.json"
        )

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        path.write_text(
            json.dumps(
                manifest,
                indent=4,
            ),
            encoding="utf-8",
        )

        print(
            "✅ Generated architectai_manifest.json"
        )

    @staticmethod
    def sanitize_k8s_name(name: str) -> str:
        """Sanitize a project name for valid Kubernetes DNS-1123 label."""
        import re
        cleaned = "".join(c if c.isalnum() or c in ("-", "_") else "-" for c in name.lower())
        cleaned = cleaned.replace("_", "-")
        cleaned = re.sub(r"-+", "-", cleaned).strip("-")
        return cleaned or "architectai-service"

    def generate_kubernetes_manifests(self, project_name: str, blueprint=None):
        k8s_name = self.sanitize_k8s_name(project_name)
        k8s_dir = self.backend_dir / "k8s"

        deployment_content = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {k8s_name}
  labels:
    app.kubernetes.io/name: {k8s_name}
    app.kubernetes.io/instance: {k8s_name}
    app.kubernetes.io/managed-by: architectai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {k8s_name}
  template:
    metadata:
      labels:
        app: {k8s_name}
    spec:
      containers:
        - name: {k8s_name}
          image: {k8s_name}:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {k8s_name}-config
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
"""
        FileWriter.write(k8s_dir / "deployment.yaml", deployment_content)

        service_content = f"""apiVersion: v1
kind: Service
metadata:
  name: {k8s_name}-service
  labels:
    app.kubernetes.io/name: {k8s_name}
    app.kubernetes.io/managed-by: architectai
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: {k8s_name}
"""
        FileWriter.write(k8s_dir / "service.yaml", service_content)

        configmap_content = f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: {k8s_name}-config
  labels:
    app.kubernetes.io/name: {k8s_name}
    app.kubernetes.io/managed-by: architectai
data:
  APP_ENV: "production"
  DEBUG: "False"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DATABASE_URL: "sqlite:////app/data/app.db"
"""
        FileWriter.write(k8s_dir / "configmap.yaml", configmap_content)

        ingress_content = f"""apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {k8s_name}-ingress
  labels:
    app.kubernetes.io/name: {k8s_name}
    app.kubernetes.io/managed-by: architectai
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {k8s_name}.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {k8s_name}-service
                port:
                  number: 80
"""
        FileWriter.write(k8s_dir / "ingress.yaml", ingress_content)

        hpa_content = f"""apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {k8s_name}-hpa
  labels:
    app.kubernetes.io/name: {k8s_name}
    app.kubernetes.io/managed-by: architectai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {k8s_name}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
"""
        FileWriter.write(k8s_dir / "hpa.yaml", hpa_content)

        kustomization_content = f"""apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: {k8s_name}-kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
"""
        FileWriter.write(k8s_dir / "kustomization.yaml", kustomization_content)
        print("✅ Generated Kubernetes manifests (deployment, service, configmap, ingress, hpa, kustomization)")

    def generate_helm_chart(self, project_name: str, blueprint=None):
        k8s_name = self.sanitize_k8s_name(project_name)
        helm_dir = self.backend_dir / "helm" / k8s_name
        templates_dir = helm_dir / "templates"

        chart_content = f"""apiVersion: v2
name: {k8s_name}
description: Helm chart for {project_name} FastAPI microservice generated by ArchitectAI
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - microservice
  - architectai
maintainers:
  - name: ArchitectAI Tech Lead
"""
        FileWriter.write(helm_dir / "Chart.yaml", chart_content)

        values_content = f"""replicaCount: 2

image:
  repository: {k8s_name}
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {{}}

podSecurityContext: {{}}

securityContext: {{}}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: "nginx"
  annotations: {{}}
  hosts:
    - host: {k8s_name}.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  APP_ENV: "production"
  DEBUG: "False"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DATABASE_URL: "sqlite:////app/data/app.db"
"""
        FileWriter.write(helm_dir / "values.yaml", values_content)

        helpers_content = f"""{{{{/*
Expand the name of the chart.
*/}}}}
{{{{- define "{k8s_name}.name" -}}}}
{{{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}}}
{{{{- end }}}}

{{{{/*
Create a default fully qualified app name.
*/}}}}
{{{{- define "{k8s_name}.fullname" -}}}}
{{{{- if .Values.fullnameOverride }}}}
{{{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}}}
{{{{- else }}}}
{{{{- $name := default .Chart.Name .Values.nameOverride }}}}
{{{{- if contains $name .Release.Name }}}}
{{{{- .Release.Name | trunc 63 | trimSuffix "-" }}}}
{{{{- else }}}}
{{{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}}}
{{{{- end }}}}
{{{{- end }}}}
{{{{- end }}}}

{{{{/*
Create chart name and version as used by the chart label.
*/}}}}
{{{{- define "{k8s_name}.chart" -}}}}
{{{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}}}
{{{{- end }}}}

{{{{/*
Common labels
*/}}}}
{{{{- define "{k8s_name}.labels" -}}}}
helm.sh/chart: {{{{ include "{k8s_name}.chart" . }}}}
{{{{ include "{k8s_name}.selectorLabels" . }}}}
{{{{- if .Chart.AppVersion }}}}
app.kubernetes.io/version: {{{{ .Chart.AppVersion | quote }}}}
{{{{- end }}}}
app.kubernetes.io/managed-by: {{{{ .Release.Service }}}}
{{{{- end }}}}

{{{{/*
Selector labels
*/}}}}
{{{{- define "{k8s_name}.selectorLabels" -}}}}
app.kubernetes.io/name: {{{{ include "{k8s_name}.name" . }}}}
app.kubernetes.io/instance: {{{{ .Release.Name }}}}
{{{{- end }}}}
"""
        FileWriter.write(templates_dir / "_helpers.tpl", helpers_content)

        tpl_deployment = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{{ include "{k8s_name}.fullname" . }}}}
  labels:
    {{{{- include "{k8s_name}.labels" . | nindent 4 }}}}
spec:
  {{{{- if not .Values.autoscaling.enabled }}}}
  replicas: {{{{ .Values.replicaCount }}}}
  {{{{- end }}}}
  selector:
    matchLabels:
      {{{{- include "{k8s_name}.selectorLabels" . | nindent 6 }}}}
  template:
    metadata:
      labels:
        {{{{- include "{k8s_name}.selectorLabels" . | nindent 8 }}}}
    spec:
      containers:
        - name: {{{{ .Chart.Name }}}}
          image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag | default .Chart.AppVersion }}}}"
          imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
          ports:
            - name: http
              containerPort: {{{{ .Values.service.targetPort }}}}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{{{ include "{k8s_name}.fullname" . }}}}-config
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{{{- toYaml .Values.resources | nindent 12 }}}}
"""
        FileWriter.write(templates_dir / "deployment.yaml", tpl_deployment)

        tpl_service = f"""apiVersion: v1
kind: Service
metadata:
  name: {{{{ include "{k8s_name}.fullname" . }}}}
  labels:
    {{{{- include "{k8s_name}.labels" . | nindent 4 }}}}
spec:
  type: {{{{ .Values.service.type }}}}
  ports:
    - port: {{{{ .Values.service.port }}}}
      targetPort: {{{{ .Values.service.targetPort }}}}
      protocol: TCP
      name: http
  selector:
    {{{{- include "{k8s_name}.selectorLabels" . | nindent 4 }}}}
"""
        FileWriter.write(templates_dir / "service.yaml", tpl_service)

        tpl_configmap = f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: {{{{ include "{k8s_name}.fullname" . }}}}-config
  labels:
    {{{{- include "{k8s_name}.labels" . | nindent 4 }}}}
data:
  {{{{- range $key, $val := .Values.env }}}}
  {{{{ $key }}}}: {{{{ $val | quote }}}}
  {{{{- end }}}}
"""
        FileWriter.write(templates_dir / "configmap.yaml", tpl_configmap)

        tpl_ingress = f"""{{{{- if .Values.ingress.enabled -}}}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{{{ include "{k8s_name}.fullname" . }}}}
  labels:
    {{{{- include "{k8s_name}.labels" . | nindent 4 }}}}
  {{{{- with .Values.ingress.annotations }}}}
  annotations:
    {{{{- toYaml . | nindent 4 }}}}
  {{{{- end }}}}
spec:
  {{{{- if .Values.ingress.className }}}}
  ingressClassName: {{{{ .Values.ingress.className }}}}
  {{{{- end }}}}
  rules:
    {{{{- range .Values.ingress.hosts }}}}
    - host: {{{{ .host | quote }}}}
      http:
        paths:
          {{{{- range .paths }}}}
          - path: {{{{ .path }}}}
            pathType: {{{{ .pathType }}}}
            backend:
              service:
                name: {{{{ include "{k8s_name}.fullname" $ }}}}
                port:
                  number: {{{{ $.Values.service.port }}}}
          {{{{- end }}}}
    {{{{- end }}}}
{{{{- end }}}}
"""
        FileWriter.write(templates_dir / "ingress.yaml", tpl_ingress)

        tpl_hpa = f"""{{{{- if .Values.autoscaling.enabled -}}}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{{{ include "{k8s_name}.fullname" . }}}}
  labels:
    {{{{- include "{k8s_name}.labels" . | nindent 4 }}}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{{{ include "{k8s_name}.fullname" . }}}}
  minReplicas: {{{{ .Values.autoscaling.minReplicas }}}}
  maxReplicas: {{{{ .Values.autoscaling.maxReplicas }}}}
  metrics:
    {{{{- if .Values.autoscaling.targetCPUUtilizationPercentage }}}}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{{{ .Values.autoscaling.targetCPUUtilizationPercentage }}}}
    {{{{- end }}}}
{{{{- end }}}}
"""
        FileWriter.write(templates_dir / "hpa.yaml", tpl_hpa)
        print("✅ Generated Helm chart (Chart.yaml, values.yaml, templates)")

    def generate(
        self,
        project_name: str,
        blueprint,
    ):
        print("\n" + "=" * 60)
        print("📦 Packaging Generated Project")
        print("=" * 60)

        self.backend_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.generate_requirements()
        self.generate_env_example()
        self.generate_dockerfile()
        self.generate_dockerignore()
        self.generate_gitignore()
        self.generate_pytest_ini()
        self.generate_kubernetes_manifests(
            project_name=project_name,
            blueprint=blueprint,
        )
        self.generate_helm_chart(
            project_name=project_name,
            blueprint=blueprint,
        )
        self.generate_openapi_spec()

        self.generate_readme(
            project_name=project_name,
            entities=blueprint.entities,
        )

        self.generate_manifest(
            project_name=project_name,
            blueprint=blueprint,
        )

        print(
            "\n✅ Project packaging completed"
        )
