"""
README Generator

Generates documentation for dynamically generated backend projects.
"""

from pathlib import Path

from generators.writer import FileWriter


class ReadmeGenerator:

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)

    def generate(self, blueprint):

        entity_names = [
            entity.name
            for entity in blueprint.entities
        ]

        entity_list = "\n".join(
            f"- {name}"
            for name in entity_names
        )

        endpoints = []

        for entity in blueprint.entities:

            lower = entity.name.lower()
            base = f"/{lower}s"

            endpoints.extend([
                f"- `POST {base}/` - Create {entity.name}",
                f"- `GET {base}/` - List {entity.name} records",
                f"- `GET {base}/{{id}}` - Get {entity.name} by ID",
                f"- `PUT {base}/{{id}}` - Update {entity.name}",
                f"- `DELETE {base}/{{id}}` - Delete {entity.name}",
            ])

        endpoint_list = "\n".join(endpoints)

        relationship_list = []

        for relationship in blueprint.relationships:

            relationship_list.append(
                f"- {relationship.source} -> "
                f"{relationship.target} "
                f"({relationship.relationship_type})"
            )

        relationships = (
            "\n".join(relationship_list)
            if relationship_list
            else "- No relationships detected"
        )

        readme = f"""# {blueprint.name}

Backend automatically generated by ArchitectAI.

## Technology Stack

- Python
- FastAPI
- SQLAlchemy
- Pydantic
- SQLite
- Pytest

## Generated Entities

{entity_list}

## Entity Relationships

{relationships}

## API Endpoints

{endpoint_list}

## Project Structure

```text
backend/
├── app/
│   ├── api/
│   ├── models/
│   ├── repositories/
│   ├── schemas/
│   ├── services/
│   ├── config.py
│   ├── database.py
│   └── main.py
├── tests/
├── .env.example
├── requirements.txt
└── README.md