"""
Backend Templates

Contains reusable FastAPI starter templates for ArchitectAI.
"""


# ==========================================================
# FastAPI Main Application
# ==========================================================

def main_template(project_name: str):

    return f'''"""
{project_name}

Generated by ArchitectAI
"""

from fastapi import FastAPI

from app.api.health import router as health_router
from app.api.patients import router as patients_router
from app.api.doctors import router as doctors_router
from app.api.appointments import router as appointments_router

app = FastAPI(
    title="{project_name}",
    version="1.0.0",
)

app.include_router(health_router)
app.include_router(patients_router)
app.include_router(doctors_router)
app.include_router(appointments_router)


@app.get("/")
def root():

    return {{
        "project": "{project_name}",
        "status": "running"
    }}
'''


# ==========================================================
# requirements.txt
# ==========================================================

def requirements_template():

    return """fastapi
uvicorn
sqlalchemy
pydantic
pydantic-settings
python-dotenv
psycopg2-binary
python-jose
passlib[bcrypt]
"""


# ==========================================================
# config.py
# ==========================================================

def config_template():

    return '''"""
Application Configuration
"""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):

    APP_NAME: str = "ArchitectAI"

    APP_VERSION: str = "1.0.0"

    DATABASE_URL: str = (
        "postgresql://postgres:postgres@localhost/hospital_db"
    )

    SECRET_KEY: str = "CHANGE_ME"

    ALGORITHM: str = "HS256"

    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30


settings = Settings()
'''


# ==========================================================
# database.py
# ==========================================================

def database_template():

    return '''"""
Database Configuration
"""

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.config import settings


engine = create_engine(
    settings.DATABASE_URL,
    echo=True,
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine,
)
'''


# ==========================================================
# .env.example
# ==========================================================

def env_template():

    return """DATABASE_URL=postgresql://postgres:postgres@localhost/hospital_db

SECRET_KEY=CHANGE_ME

APP_ENV=development
"""


# ==========================================================
# Health API
# ==========================================================

def health_api_template():

    return '''"""
Health API
"""

from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health():

    return {
        "status": "healthy",
        "service": "ArchitectAI"
    }
'''


# ==========================================================
# Patients API
# ==========================================================

def patients_api_template():

    return '''"""
Patients API
"""

from fastapi import APIRouter

router = APIRouter(
    prefix="/patients",
    tags=["Patients"]
)


@router.get("/")
def list_patients():

    return {
        "message": "List of patients"
    }


@router.post("/")
def create_patient():

    return {
        "message": "Patient created"
    }
'''

#Patient Model

def patient_model_template():

    return '''"""
Patient Model
"""

from sqlalchemy import Column, Integer, String

from app.database import engine
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Patient(Base):

    __tablename__ = "patients"

    id = Column(Integer, primary_key=True, index=True)

    name = Column(String, nullable=False)

    age = Column(Integer)

    gender = Column(String)

    phone = Column(String)


Base.metadata.create_all(bind=engine)
'''

#Patient Schema

def patient_schema_template():

    return '''"""
Patient Schema
"""

from pydantic import BaseModel


class PatientCreate(BaseModel):

    name: str

    age: int

    gender: str

    phone: str


class PatientResponse(PatientCreate):

    id: int

    class Config:

        from_attributes = True
'''

#Patient Service

def patient_service_template():

    return '''"""
Patient Service
"""

from app.models.patient import Patient


class PatientService:

    @staticmethod
    def create_patient(data):

        return Patient(**data)

    @staticmethod
    def list_patients():

        return []
'''

#Patient Repository

def patient_repository_template():

    return '''"""
Patient Repository
"""

from sqlalchemy.orm import Session

from app.models.patient import Patient


class PatientRepository:

    @staticmethod
    def get_all(db: Session):

        return db.query(Patient).all()
'''






# ==========================================================
# Doctors API
# ==========================================================

def doctors_api_template():

    return '''"""
Doctors API
"""

from fastapi import APIRouter

router = APIRouter(
    prefix="/doctors",
    tags=["Doctors"]
)


@router.get("/")
def list_doctors():

    return {
        "message": "List of doctors"
    }


@router.post("/")
def create_doctor():

    return {
        "message": "Doctor created"
    }
'''


# ==========================================================
# Appointments API
# ==========================================================

def appointments_api_template():

    return '''"""
Appointments API
"""

from fastapi import APIRouter

router = APIRouter(
    prefix="/appointments",
    tags=["Appointments"]
)


@router.get("/")
def list_appointments():

    return {
        "message": "List of appointments"
    }


@router.post("/")
def create_appointment():

    return {
        "message": "Appointment created"
    }
'''